name: Venda Electronics 2.0
favicon: null
layout_spectrum: 0.5433337788563222
typography_spectrum: 0.3075310711283237
title: Venda Electronics
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
  brandStrength: 0.8366812444292009
  lightness: 0.2432936041150242
  saturation: 0.6791670715902001
  rhythmicContrast: 0.20349311968311667
purpose: []
