typography_spectrum: 0.15707304095849395
color:
  brandColors:
    - '#F7F2B2'
    - '#ADCF4F'
    - '#84815B'
    - '#4A1A2C'
    - '#8E3557'
  brandStrength: 0.9633815353736281
  lightness: 0.7648829852696508
  saturation: 0.0031055232975631952
  rhythmicContrast: 0.05897899344563484
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7078307126648724
analytics:
  google: null
  facebook: null
  twitter: null
name: Vanda Electronics 2.0
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: were we CREATE
    id: 3d88b6af-fa51-44b6-8a64-ae2e50d8a469
    type: content
  - name: a little about US
    id: e3acf9b3-446b-4956-a6a8-2737a23c4966
    type: content
  - name: our PROUDUCTS
    id: 3006d071-248f-4554-ae2f-69d8ead9ceff
    type: content
favicon: null
title: Vanda Electronics
purpose: []
