typography_spectrum: 0.76771
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6875
  lightness: 0.3551420848816633
  saturation: 0.3226485827472061
  rhythmicContrast: 0.4248277398291975
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.53168
analytics:
  google: null
  facebook: null
  twitter: null
name: Venda Electronics 2.0
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: were we CREATE
    id: 3d88b6af-fa51-44b6-8a64-ae2e50d8a469
    type: content
  - name: a little about US
    id: e3acf9b3-446b-4956-a6a8-2737a23c4966
    type: content
favicon: null
title: Venda Electronics
purpose: []
